export enum HttpReasonPhrases {
  ACCEPTED = "Accepted",
  BAD_REQUEST = "Bad Request",
  CREATED = "Created",
  FORBIDDEN = "Forbidden",
  INSUFFICIENT_SPACE_ON_RESOURCE = "Insufficient Space on Resource",
  INSUFFICIENT_STORAGE = "Insufficient Storage",
  INTERNAL_SERVER_ERROR = "Internal Server Error",
  METHOD_NOT_ALLOWED = "Method Not Allowed",
  NOT_ACCEPTABLE = "Not Acceptable",
  NOT_FOUND = "Not Found",
  NOT_IMPLEMENTED = "Not Implemented",
  OK = "OK",
  PARTIAL_CONTENT = "Partial Content",
  PROCESSING = "Processing",
  REQUEST_TIMEOUT = "Request Timeout",
  SERVICE_UNAVAILABLE = "Service Unavailable",
  TOO_MANY_REQUESTS = "Too Many Requests",
  UNAUTHORIZED = "Unauthorized",
  UNSUPPORTED_MEDIA_TYPE = "Unsupported Media Type",
}
